package group92.spectrangle.view;

import javax.swing.*;
import java.awt.*;

public class GUIServerBrowser {
    private JButton changeUsernameButton;
    private JButton addServerManuallyButton;
    private JList serverList;
    private JLabel usernameField;
    private JPanel optionPanel;
    private JPanel mainPanel;
    private JButton createServerButton;
    private JButton refreshButton;

    public static void main(String[] args) {
        JFrame frame = new JFrame("Spectrangle");
        frame.setContentPane(new GUIServerBrowser().mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        optionPanel = new JPanel();
        optionPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        mainPanel.add(optionPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        usernameField = new JLabel();
        usernameField.setText("[username]");
        optionPanel.add(usernameField);
        changeUsernameButton = new JButton();
        changeUsernameButton.setText("Change username");
        optionPanel.add(changeUsernameButton);
        addServerManuallyButton = new JButton();
        addServerManuallyButton.setText("Add server manually");
        optionPanel.add(addServerManuallyButton);
        createServerButton = new JButton();
        createServerButton.setText("Create Server");
        optionPanel.add(createServerButton);
        refreshButton = new JButton();
        refreshButton.setText("Refresh");
        optionPanel.add(refreshButton);
        serverList = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        serverList.setModel(defaultListModel1);
        mainPanel.add(serverList, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
